"""Per-source validity is enforced after Pydantic parse and surfaces as 422."""
import pytest

from app.reports import sources as registry
from app.schemas.reports_query import (
    Aggregation, Dataset, Dimension, Filter, FilterField, FilterOp,
    Measure, MeasureField, ReportsQuery,
)


def _q(dataset, measure, dims=None, filters=None):
    return ReportsQuery(
        dataset=dataset, measure=measure,
        dimensions=dims or [], filters=filters or [],
    )


def test_transactions_rejects_balance_measure():
    src = registry.get_source("transactions")
    q = _q(Dataset.TRANSACTIONS, Measure(agg=Aggregation.SUM, field=MeasureField.BALANCE))
    with pytest.raises(ValueError):
        src.validate(q)


def test_transactions_rejects_an_out_of_source_dimension():
    """⚠ RE-POINTED, NOT DELETED (TBD-507).

    This test guards ``validate_against_catalog``'s dimension arm -- that the
    catalog rejects a dimension the source does not publish. It is not about any
    particular dimension, and it has now been re-pointed TWICE:

    * originally ``currency``, until TBD-507 published that on transactions;
    * then ``account_type``, until TBD-471 (one day later) published that too.

    ⚠ ``recurring_active`` is the current target, and an earlier version of this
    docstring justified it by calling it "structurally impossible for this
    source". THAT IS FALSE and was caught in review: ``Transaction.recurring_id``
    exists (``models/transaction.py:117``) with a ``recurring`` relationship, so
    "rows generated by an active recurring template" is exactly one join away --
    the same shape as ``account_type``, which ``Transaction`` also lacks directly
    and reaches through ``Account``.

    So this test WILL need re-pointing again if that dimension is ever
    published. That is acceptable and cheap; what is not acceptable is the next
    reader believing the target was chosen for a guarantee that does not exist,
    and therefore trusting it to stay valid. The test is about the ARM, not the
    dimension: keep the arm covered, move the target when you must.
    """
    src = registry.get_source("transactions")
    q = _q(Dataset.TRANSACTIONS,
           Measure(agg=Aggregation.SUM, field=MeasureField.AMOUNT),
           dims=[Dimension.RECURRING_ACTIVE])
    with pytest.raises(ValueError):
        src.validate(q)


def test_transactions_now_accepts_the_currency_dimension():
    """The other half of the inversion above: what used to be rejected is the
    feature. Without this, re-pointing the test above would leave the currency
    dimension unasserted at the validation layer."""
    src = registry.get_source("transactions")
    q = _q(Dataset.TRANSACTIONS,
           Measure(agg=Aggregation.SUM, field=MeasureField.AMOUNT),
           dims=[Dimension.CURRENCY])
    src.validate(q)


def test_transactions_accepts_its_own_surface():
    src = registry.get_source("transactions")
    q = _q(Dataset.TRANSACTIONS,
           Measure(agg=Aggregation.SUM, field=MeasureField.AMOUNT),
           dims=[Dimension.CATEGORY])
    src.validate(q)  # no raise


def test_transactions_accepts_status_eq():
    src = registry.get_source("transactions")
    q = _q(Dataset.TRANSACTIONS,
           Measure(agg=Aggregation.SUM, field=MeasureField.AMOUNT),
           filters=[Filter(field=FilterField.STATUS, op=FilterOp.EQ, value="settled")])
    src.validate(q)  # no raise — transactions publishes status (eq)


def test_transactions_rejects_status_non_eq_op():
    # ``status`` is now a shared-canvas field, but transactions publishes it
    # as eq-only; a non-eq op must still 422 at validate (not be silently
    # dropped by the shared-canvas branch), so the published-field op-check
    # stays intact.
    src = registry.get_source("transactions")
    q = _q(Dataset.TRANSACTIONS,
           Measure(agg=Aggregation.SUM, field=MeasureField.AMOUNT),
           filters=[Filter(field=FilterField.STATUS, op=FilterOp.IN,
                           value=["settled", "pending"])])
    with pytest.raises(ValueError):
        src.validate(q)
