#!/usr/bin/env node
/**
 * Compares this run's act() warning tally against the committed baseline.
 * TBD-393.
 *
 *   node tests/act-guard/judge.mjs check     # exit 1 on ANY difference
 *   node tests/act-guard/judge.mjs --write   # regenerate the baseline
 *
 * STRICT EQUALITY, INCLUDING DECREASES. This is the whole design and it is
 * counter-intuitive, so it is written down here rather than only in the PR.
 *
 * Every way this gate can die silently produces the SAME observable: the
 * counts drop. Hook not installed; matcher no longer matches React's format;
 * the name read from the wrong console.error argument; the task-meta channel
 * broken by a Vitest upgrade; the reporter flag dropped from the npm script;
 * a test file blanket-silencing console.error. A gate that permits decreases
 * cannot tell any of those apart from "we fixed some warnings" -- it is
 * structurally incapable of detecting its own death, which is exactly the
 * vacuity this ticket exists to avoid.
 *
 * Under strict equality, the day the detector dies CI goes red on
 * tests/act-guard/self-test.test.tsx > ActCanary: expected 1, got 0. The gate
 * re-proves itself on every run instead of on the day it landed.
 *
 * The cost is real and accepted: a PR that fixes act warnings must commit a
 * lower number. That hunk is the evidence of the fix, and it is reviewable.
 * This mirrors frontend/tests/fixtures/report-sources.json and
 * backend/.test_durations, which both FAIL rather than self-regenerate for
 * the same reason.
 */

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const BASELINE = resolve(HERE, "act-baseline.json");
const ARTIFACT = resolve(process.cwd(), ".act-warnings.json");
const REGEN = "npm run act:baseline -- --write";

const mode = process.argv[2] === "--write" ? "write" : "check";
const inCI = Boolean(process.env.CI);

function die(msg) {
  console.error("\n" + msg + "\n");
  process.exit(1);
}

if (!existsSync(ARTIFACT)) {
  die(
    "act() warning gate (TBD-393): no .act-warnings.json was produced.\n" +
      "The reporter did not run. Check that the test script still passes\n" +
      "  --reporter=./tests/act-guard/reporter.ts\n" +
      "A missing artifact fails hard on purpose: treating it as 'no warnings'\n" +
      "is precisely how this gate would die silently.",
  );
}

const run = JSON.parse(readFileSync(ARTIFACT, "utf8"));

// A sharded run only ever sees a slice. Comparing a slice against the full
// baseline would fail spuriously; SKIPPING would silently downgrade the gate.
// Refuse instead, so introducing --shard is a deliberate act.
if (run.shard) {
  die(
    "act() warning gate (TBD-393): this run was sharded.\n" +
      "The gate compares whole-suite tallies and has no merge step yet.\n" +
      "Either run unsharded, or teach judge.mjs to merge shard artifacts.",
  );
}

// `npm test -- tests/foo.test.tsx` is the documented dev workflow. Locally
// that is fine and we say so; in CI it must never happen, because adding a
// filter to the workflow would quietly disarm the gate.
if (run.partial) {
  if (inCI) {
    die(
      "act() warning gate (TBD-393): the CI run was FILTERED and cannot be judged.\n" +
        "argv: " + JSON.stringify(run.argv) + "\n" +
        "The gate must see the whole suite. Remove the filter.",
    );
  }
  console.log(
    "act() warning gate (TBD-393): run was filtered -- gate not armed. " +
      "Run the full suite to compare against the baseline.",
  );
  process.exit(0);
}

if (mode === "write") {
  if (inCI) {
    die(
      "act() warning gate (TBD-393): refusing to regenerate the baseline under CI.\n" +
        "A baseline regenerated by the very run it is meant to gate can never fail.\n" +
        "Regenerate locally and commit the diff.",
    );
  }
  const previous = existsSync(BASELINE)
    ? JSON.parse(readFileSync(BASELINE, "utf8")).files ?? {}
    : {};
  // Preserve keys that dropped to zero as explicit tombstones rather than
  // pruning them. A tombstone states "these were eliminated, do not
  // reintroduce"; a deleted entry states nothing, and makes a rename
  // indistinguishable from a fix in the diff.
  const files = {};
  for (const [file, comps] of Object.entries(previous)) {
    files[file] = Object.fromEntries(Object.keys(comps).map((c) => [c, 0]));
  }
  for (const [file, comps] of Object.entries(run.files)) {
    files[file] = { ...(files[file] ?? {}), ...comps };
  }
  const sorted = Object.fromEntries(
    Object.entries(files)
      .sort()
      .map(([f, c]) => [f, Object.fromEntries(Object.entries(c).sort())]),
  );
  writeFileSync(
    BASELINE,
    JSON.stringify(
      {
        schemaVersion: 1,
        note: "GENERATED by `" + REGEN + "`. Never hand-edit. TBD-393.",
        files: sorted,
      },
      null,
      2,
    ) + "\n",
  );
  const total = Object.values(sorted)
    .flatMap((c) => Object.values(c))
    .reduce((a, b) => a + b, 0);
  console.log(
    "act() warning baseline written: " +
      Object.keys(sorted).length + " files, " + total + " warnings.",
  );
  process.exit(0);
}

if (!existsSync(BASELINE)) {
  die("act() warning gate (TBD-393): no baseline. Generate one with:\n  " + REGEN);
}

const base = JSON.parse(readFileSync(BASELINE, "utf8")).files ?? {};

// Compare on the (file, component) pair. A per-component total would let a
// fix in one test file absorb a regression in another: DataTab's warnings
// span 7 files and DashboardDataProvider's span 12, so that offsetting is
// not hypothetical.
// Build the union of (file, component) pairs. Deliberately a nested map
// rather than a joined string key: a separator character that cannot appear
// in a path or a component name does not exist, and the obvious candidates
// either collide (a space is legal in both) or make this file binary to git,
// which costs the diff its reviewability.
const pairs = new Map();
for (const source of [base, run.files]) {
  for (const [file, comps] of Object.entries(source)) {
    if (!pairs.has(file)) pairs.set(file, new Set());
    for (const comp of Object.keys(comps)) pairs.get(file).add(comp);
  }
}

const worse = [];
const better = [];
for (const file of [...pairs.keys()].sort()) {
  for (const comp of [...pairs.get(file)].sort()) {
    const want = base[file]?.[comp] ?? 0;
    const got = run.files[file]?.[comp] ?? 0;
    if (got > want) worse.push({ file, comp, want, got });
    else if (got < want) better.push({ file, comp, want, got });
  }
}

if (worse.length === 0 && better.length === 0) {
  const total = Object.values(run.files)
    .flatMap((c) => Object.values(c))
    .reduce((a, b) => a + b, 0);
  console.log(
    "act() warning gate (TBD-393): OK -- " + total + " warnings, matching baseline.",
  );
  process.exit(0);
}

const fmt = (rows) =>
  rows
    .map((r) => "    " + r.file + " > " + r.comp + ": expected " + r.want + ", got " + r.got)
    .join("\n");

let msg = "act() warning baseline mismatch (TBD-393)\n";
if (worse.length) {
  msg +=
    "\n  NEW act() warnings -- a state update escaped its act() scope.\n" +
    "  Wrap the update, or await the component's real settle point:\n" +
    fmt(worse) +
    "\n";
}
if (better.length) {
  msg +=
    "\n  FEWER act() warnings than the baseline.\n" +
    "  If you fixed these, regenerate and commit the baseline:\n" +
    "      " + REGEN + "\n" +
    "  If you did NOT fix them, the DETECTOR IS BROKEN and this is the\n" +
    "  symptom. Counts collapsing to zero is what a dead hook, a drifted\n" +
    "  matcher, or a broken task-meta channel looks like. Check\n" +
    "  tests/act-guard/self-test.test.tsx > ActCanary first -- it is pinned\n" +
    "  at 1 and can only read 1 if the whole chain works:\n" +
    fmt(better) +
    "\n";
}
die(msg);
