import datetime
from decimal import Decimal
from typing import Literal, Optional

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from app.schemas.tag import MAX_TAGS_PER_TRANSACTION, TagResponse


class TransactionCreate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    account_id: int
    category_id: int
    description: str = Field(max_length=255)
    amount: Decimal = Field(gt=0, max_digits=12, decimal_places=2)
    type: Literal["income", "expense"]
    status: Literal["settled", "pending"] = "settled"
    date: datetime.date
    # Optional expected settlement date for pending rows. When status=pending
    # and the user provides this, it surfaces in the period bucket
    # (effective_period_date_expr) so forecasts and period filters see the
    # row in its expected month rather than its purchase month. Stored
    # as-is for SETTLED rows when explicitly supplied; the service layer
    # falls back to the transaction date if omitted on SETTLED creates so
    # the SETTLED-implies-settled_date invariant holds.
    settled_date: Optional[datetime.date] = None

    @field_validator("description")
    @classmethod
    def description_not_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("Description is required")
        return v.strip()

    @model_validator(mode="after")
    def _settled_date_not_before_date(self) -> "TransactionCreate":
        if self.settled_date is not None and self.settled_date < self.date:
            raise ValueError("settled_date must be on or after date")
        return self


class TransferCreate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    from_account_id: int
    to_account_id: int
    category_id: Optional[int] = None
    description: str = Field(default="", max_length=255)
    amount: Decimal = Field(gt=0, max_digits=12, decimal_places=2)
    status: Literal["settled", "pending"] = "settled"
    date: datetime.date


class TransactionUpdate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    account_id: Optional[int] = None
    category_id: Optional[int] = None
    description: Optional[str] = None
    amount: Optional[Decimal] = Field(default=None, gt=0, max_digits=12, decimal_places=2)
    type: Optional[Literal["income", "expense"]] = None
    status: Optional[Literal["settled", "pending"]] = None
    settled_date: Optional[datetime.date] = None
    date: Optional[datetime.date] = None

    @field_validator("description")
    @classmethod
    def description_not_empty(cls, v: str | None) -> str | None:
        if v is not None and not v.strip():
            raise ValueError("Description is required")
        return v.strip() if v is not None else v


class TransactionResponse(BaseModel):
    id: int
    account_id: int
    account_name: str = ""
    category_id: int
    category_name: str = ""
    description: str
    amount: Decimal
    type: Literal["income", "expense"]
    status: Literal["settled", "pending"]
    linked_transaction_id: Optional[int] = None
    # TBD-268: the partner leg's account name, so a collapsed transfer row can
    # render "source -> destination" without the partner being in the page.
    # Populated ONLY for a MUTUAL, same-org link (a one-way reconciliation
    # match leaves this None), and only when the caller passed
    # collapse_transfers=true - the eager load is gated on it.
    linked_account_name: Optional[str] = None
    recurring_id: Optional[int] = None
    date: datetime.date
    settled_date: datetime.date | None = None
    is_imported: bool = False
    # Track E: True for rows generated by POST /accounts/{id}/adjust-balance.
    # Frontend can use this to render a distinct visual treatment (deferred
    # to a follow-up PR per the architect spec).
    is_manual_adjustment: bool = False
    # PR-Tags-A contract: list/detail responses include the tags
    # attached to a transaction. Empty list when none. Populated via a
    # selectinload in transaction_service.list_transactions /
    # get_transaction so the join is one extra query, not N+1.
    tags: list[TagResponse] = Field(default_factory=list)

    model_config = {"from_attributes": True}


class BulkDeleteRequest(BaseModel):
    """Body for POST /api/v1/transactions/bulk-delete."""

    model_config = ConfigDict(extra="forbid")

    ids: list[int] = Field(
        ...,
        min_length=1,
        max_length=500,
        description="Transaction IDs to delete. Cross-org IDs are silently ignored. Transfer-pair halves cascade.",
    )


class PromoteToRecurringRequest(BaseModel):
    """Body for POST /api/v1/transactions/{id}/promote-to-recurring.

    Promotes an existing settled-or-pending transaction into a recurring
    template (creates a RecurringTransaction with the tx's account/category/
    amount/type/description and the supplied schedule, then sets
    transaction.recurring_id to the new template).

    Account, category, amount, type, and description come from the source
    transaction. ``auto_settle`` is optional and defaults to False to match
    the standalone recurring-create flow; the create-transaction-with-repeat
    UI passes it through so the user's choice is preserved without needing
    a separate POST /recurring round-trip. Out of scope: promoting transfer
    legs, demoting.

    ⚠ ``next_due_date`` carries NO schema-level lower bound, deliberately
    (TBD-283). It used to reject anything before ``date.today()`` here, which
    made promote strictly stricter than ``create_recurring`` and
    ``update_recurring`` on the same field of the same table. The real bound is
    the org's current billing cycle start, which needs
    ``org.billing_cycle_day`` and therefore a DB read; a pydantic validator
    cannot express it and would only ever pre-empt it with a different rule.
    ``recurring_service.validate_frontier`` is the one enforcement point, and
    it rejects with 400, not 422.
    """

    model_config = ConfigDict(extra="forbid")

    frequency: Literal["weekly", "biweekly", "monthly", "quarterly", "yearly"]
    next_due_date: datetime.date
    auto_settle: bool = False
    # TBD-275: total instalments INCLUDING the source transaction. Promotion is
    # how an instalment plan is normally born ("I just paid the first of 12"),
    # so the source transaction IS instalment 1.
    #
    # ⚠ Whether the template is seeded with ``occurrences_elapsed`` 1 or 0
    # depends on THIS field's relation to the source row's date, and
    # ``transaction_service.promote_to_recurring`` is the one place that
    # decision is written. A ``next_due_date`` strictly AFTER the source date
    # is instalment 2, so 1. A ``next_due_date`` on or before it IS instalment
    # 1, which generation's ``exists`` probe consumes, so 0. Seeding 1
    # unconditionally loses an instalment on the second shape; seeding 0
    # unconditionally delivers 13 for a 12-instalment plan on the first.
    occurrence_count: Optional[int] = Field(default=None, gt=0, le=1200)


class DeleteTransactionResponse(BaseModel):
    """Result of a single delete.

    TBD-294: ``demoted_ids`` lists rows that pointed AT the deleted row and
    were marked REJECTED so the FK's ``ON DELETE SET NULL`` could not turn
    them back into ordinary, balance-contributing transactions. REJECTED is
    terminal and unreachable through ``TransactionUpdate``, so the demotion
    is irreversible through the API -- it is reported, never silent.
    """

    deleted: bool = True
    demoted_ids: list[int] = Field(default_factory=list)


class BulkDeleteResponse(BaseModel):
    """Result of a bulk delete."""

    requested_count: int
    deleted_count: int
    skipped_ids: list[int]  # IDs that were requested but not found in this org
    # TBD-294 -- see DeleteTransactionResponse.
    demoted_ids: list[int] = Field(default_factory=list)


class BulkUpdateRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    ids: list[int] = Field(..., min_length=1, max_length=500)
    category_id: Optional[int] = None
    status: Optional[Literal["settled", "pending"]] = None
    account_id: Optional[int] = None
    # Tags are ADDED (merged) to each eligible row, not replaced. Capped at the
    # per-transaction max for the number you can add in one batch call.
    tags: Optional[list[str]] = Field(default=None, max_length=MAX_TAGS_PER_TRANSACTION)

    @model_validator(mode="after")
    def _at_least_one_field(self) -> "BulkUpdateRequest":
        # An empty tags list is a no-op (tags merge nothing), so it does not
        # count as a provided field — reject it like an all-empty request.
        if (
            self.category_id is None
            and self.status is None
            and self.account_id is None
            and not self.tags
        ):
            raise ValueError("Provide at least one field to update")
        return self


class BulkUpdateSkip(BaseModel):
    id: int
    reason: str


class BulkUpdateResponse(BaseModel):
    requested_count: int
    updated_count: int
    skipped: list[BulkUpdateSkip]


class TransactionPairRequest(BaseModel):
    """Op-1 bulk-link / import-confirm-pair / Op-2 pair-with-existing payload."""

    model_config = ConfigDict(extra="forbid")

    expense_id: int
    income_id: int
    transfer_category_id: int | None = None
    recategorize: bool = True


class ConvertToTransferRequest(BaseModel):
    """Op-2 (pair existing) + Op-3 (create missing leg) per-row payload.

    If pair_with_transaction_id is set, the candidate's account_id MUST equal
    destination_account_id (server validates and raises ValidationError on
    mismatch). If unset, the service creates the partner leg on
    destination_account_id.
    """

    model_config = ConfigDict(extra="forbid")

    destination_account_id: int
    pair_with_transaction_id: int | None = None
    transfer_category_id: int | None = None
    recategorize: bool = True


class UnpairTransactionRequest(BaseModel):
    """Op-4 unlink payload. Per-leg fallback categories required because the
    Transfer system category no longer fits once the rows are unlinked.
    """

    model_config = ConfigDict(extra="forbid")

    expense_fallback_category_id: int
    income_fallback_category_id: int


class TransferCandidate(BaseModel):
    """A potential pair candidate returned by GET /transfer-candidates and
    embedded in import preview rows when transfer_match_action requires the
    user to choose.
    """

    id: int
    date: datetime.date
    settled_date: Optional[datetime.date] = None
    description: str
    amount: Decimal
    account_id: int
    account_name: str
    date_diff_days: int
    confidence: Literal["same_day", "near_date"]


class TransferCandidatesResponse(BaseModel):
    """Wrapper for GET /api/v1/transactions/{id}/transfer-candidates."""

    candidates: list[TransferCandidate]


class SpendingCategoryRow(BaseModel):
    """One category's SETTLED, reportable expense inside a billing period.

    ``executed`` is a string (a string-serialised Decimal), matching the wire
    contract ``ForecastCategoryRow`` already uses for the same number.

    ⚠ There is no ``pending``, ``recurring`` or ``forecast`` field, and adding
    one is not an extension — those are synthesized from templates that have
    not materialised, which is the Forecast product and stays behind the
    Forecast gate (TBD-197). This row is historical actuals only; the cut line
    is happened-vs-projected.
    """

    category_id: int
    category_name: str
    parent_id: Optional[int] = None
    executed: str


class SpendingByCategoryResponse(BaseModel):
    """``GET /api/v1/transactions/spending-by-category`` (TBD-221).

    ``executed_expense`` is the sum of ``categories[].executed`` by
    construction, so the donut's centre figure can never disagree with its
    slices. ``period_end`` is the period's spend-window end, which for an open
    period is floored at today — not a calendar month end.
    """

    period_start: datetime.date
    period_end: datetime.date
    executed_expense: str
    categories: list[SpendingCategoryRow]


class DuplicateCandidate(BaseModel):
    """Embedded in ImportPreviewRow when a CSV row matches an existing linked
    leg on the same account. Lean shape so /import does not refetch row details.

    The synthetic-leg badge keys off existing_leg_is_imported (the matched leg
    itself, not its partner). False means the matched leg was created via Op-3
    convert-and-create or via the manual create-transfer UI.
    """

    id: int
    date: datetime.date
    description: str
    amount: Decimal
    account_id: int
    account_name: str
    existing_leg_is_imported: bool
